// CREATED: 2026-03-18
// UPDATED: 2026-03-18 14:00 IST (Jerusalem)
//          - Removed assignedStaffId (migrated to client_staff junction table)

import { supabase } from '@/integrations/supabase/client';
import type { Client, CreateClientInput, UpdateClientInput } from '@/types';

// Map a Supabase DB row (snake_case) to a Client object (camelCase)
function rowToClient(row: Record<string, unknown>): Client {
  return {
    id: row.id as string,
    firm_id: row.firm_id as string,
    name: row.name as string,
    caseNum: row.case_num as string,
    status: row.status as Client['status'],
    type: row.type as Client['type'],
    clientType: row.client_type as Client['clientType'],
    taxId: (row.tax_id as string) ?? undefined,
    mobile: (row.mobile as string) ?? undefined,
    email: (row.email as string) ?? undefined,
    address: (row.address as string) ?? undefined,
    city: (row.city as string) ?? undefined,
    tags: (row.tags as string[]) ?? [],
    monthlyFee: (row.monthly_fee as number) ?? 0,
    billingDay: (row.billing_day as number) ?? undefined,
    notes: (row.notes as string) ?? undefined,
    deleted_at: (row.deleted_at as string) ?? undefined,
    created_at: row.created_at as string,
    updated_at: row.updated_at as string,
  };
}

// Map camelCase input to snake_case DB columns for INSERT.
// Note: caseNum and status are excluded from CreateClientInput (set by service/DB).
function clientInputToRow(input: CreateClientInput): Record<string, unknown> {
  return {
    name: input.name,
    status: 'active',  // Always active on creation; service layer controls this
    type: input.type,
    client_type: input.clientType,
    tax_id: input.taxId ?? null,
    mobile: input.mobile ?? null,
    email: input.email ?? null,
    address: input.address ?? null,
    city: input.city ?? null,
    tags: input.tags ?? [],
    monthly_fee: input.monthlyFee ?? 0,
    billing_day: input.billingDay ?? null,
    notes: input.notes ?? null,
    case_num: '', // Safety net for NOT NULL constraint — DB trigger overwrites with generated value
  };
}

// Map camelCase partial update to snake_case DB columns
function updateInputToRow(input: UpdateClientInput): Record<string, unknown> {
  const row: Record<string, unknown> = {};
  if (input.name !== undefined) row.name = input.name;
  if (input.status !== undefined) row.status = input.status;
  if (input.type !== undefined) row.type = input.type;
  if (input.clientType !== undefined) row.client_type = input.clientType;
  if (input.taxId !== undefined) row.tax_id = input.taxId;
  if (input.mobile !== undefined) row.mobile = input.mobile;
  if (input.email !== undefined) row.email = input.email;
  if (input.address !== undefined) row.address = input.address;
  if (input.city !== undefined) row.city = input.city;
  if (input.tags !== undefined) row.tags = input.tags;
  if (input.monthlyFee !== undefined) row.monthly_fee = input.monthlyFee;
  if (input.billingDay !== undefined) row.billing_day = input.billingDay;
  if (input.notes !== undefined) row.notes = input.notes;
  return row;
}

export const clientService = {
  /** Fetch all non-deleted clients for a firm. */
  async list(firmId: string): Promise<Client[]> {
    const { data, error } = await supabase
      .from('clients')
      .select('*')
      .eq('firm_id', firmId)
      .is('deleted_at', null)
      .order('created_at', { ascending: false });

    if (error) throw new Error(error.message);
    return (data as Record<string, unknown>[]).map(rowToClient);
  },

  /** Fetch a single client by ID. firm_id filter provides defense-in-depth beyond RLS. */
  async getById(firmId: string, id: string): Promise<Client> {
    const { data, error } = await supabase
      .from('clients')
      .select('*')
      .eq('id', id)
      .eq('firm_id', firmId)
      .is('deleted_at', null)
      .maybeSingle();

    if (error) throw new Error(error.message);
    if (!data) throw new Error('Client not found');
    return rowToClient(data as Record<string, unknown>);
  },

  /** Create a new client. firm_id is set server-side, case_num is auto-generated by trigger. */
  async create(firmId: string, input: CreateClientInput): Promise<Client> {
    const row = clientInputToRow(input);
    row.firm_id = firmId;

    const { data, error } = await supabase
      .from('clients')
      .insert(row)
      .select('*')
      .single();

    if (error) throw new Error(error.message);
    return rowToClient(data as Record<string, unknown>);
  },

  /** Update an existing client. firm_id filter provides defense-in-depth beyond RLS. */
  async update(firmId: string, id: string, input: UpdateClientInput): Promise<Client> {
    const row = updateInputToRow(input);

    const { data, error } = await supabase
      .from('clients')
      .update(row)
      .eq('id', id)
      .eq('firm_id', firmId)
      .select('*')
      .single();

    if (error) throw new Error(error.message);
    return rowToClient(data as Record<string, unknown>);
  },

  /** Archive a client (set status to 'archived'). firm_id filter provides defense-in-depth beyond RLS. */
  async archive(firmId: string, id: string): Promise<void> {
    const { error } = await supabase
      .from('clients')
      .update({ status: 'archived' })
      .eq('id', id)
      .eq('firm_id', firmId);

    if (error) throw new Error(error.message);
  },

  /** Restore an archived client (set status to 'active'). firm_id filter provides defense-in-depth beyond RLS. */
  async restore(firmId: string, id: string): Promise<void> {
    const { error } = await supabase
      .from('clients')
      .update({ status: 'active' })
      .eq('id', id)
      .eq('firm_id', firmId);

    if (error) throw new Error(error.message);
  },

  /** Soft delete a client (set deleted_at). firm_id filter provides defense-in-depth beyond RLS. */
  async delete(firmId: string, id: string): Promise<void> {
    const { error } = await supabase
      .from('clients')
      .update({ deleted_at: new Date().toISOString() })
      .eq('id', id)
      .eq('firm_id', firmId);

    if (error) throw new Error(error.message);
  },
};
